version: '3'
services:
  mcp-server:
    image: mcp-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/config:/app/config
      - ./server/data:/app/data
    restart: always
    environment:
      - NODE_ENV=production
      - MCP_UPDATE_INTERVAL=3600
    networks:
      - mcp-network

  mcp-client:
    image: mcp-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - mcp-server
    ports:
      - "3000:3000"
    volumes:
      - ./client/config:/app/config
    restart: always
    environment:
      - MCP_SERVER_URL=ws://mcp-server:8080
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 
