@echo off
REM ============================================================================
REM Schwab API Data Fetcher Batch File
REM ============================================================================
REM
REM Purpose: This batch file provides an easy way to run the schwab_api_data_fetcher.py
REM          script with common parameters. It handles environment setup and provides
REM          error checking to ensure the script runs correctly.
REM
REM Usage:   Simply run this batch file without parameters to fetch quotes for
REM          default symbols (AAPL, MSFT, GOOGL)
REM
REM          Or modify the parameters in this file to customize the data fetching
REM
REM Author:  Generated by Roo
REM Date:    April 29, 2025
REM ============================================================================

echo.
echo Schwab API Data Fetcher
echo =============================================
echo.

REM Check if Python is installed
where python >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Python is not installed or not in the PATH.
    echo Please install Python 3.10 or higher and try again.
    goto :EOF
)

REM Check Python version
python --version | findstr /r "3\.[1-9][0-9]" >nul
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Python version may not be compatible.
    echo Recommended: Python 3.10 or higher.
    echo.
    timeout /t 3
)

REM Check if the script exists
if not exist "schwab_api_data_fetcher.py" (
    echo ERROR: schwab_api_data_fetcher.py not found in the current directory.
    echo Please ensure you're running this batch file from the correct directory.
    goto :EOF
)

echo Setting up Python environment...
echo.

REM Activate virtual environment if it exists
if exist "venv\Scripts\activate.bat" (
    call venv\Scripts\activate.bat
    echo Virtual environment activated.
) else (
    echo No virtual environment found. Using system Python.
)

echo.
echo =============================================
echo Example commands (commented out):
echo =============================================
echo.

REM Example 1: Fetch quotes for default symbols
REM python schwab_api_data_fetcher.py --symbols AAPL,MSFT,GOOGL

REM Example 2: Fetch price history for SPY
REM python schwab_api_data_fetcher.py --symbols SPY --data-type price-history

REM Example 3: Fetch quotes with JSON output
REM python schwab_api_data_fetcher.py --symbols AAPL,MSFT --output json

REM Example 4: Fetch price history for QQQ with specific period and frequency
REM python schwab_api_data_fetcher.py --symbols QQQ --data-type price-history --period 30 --period-type day --frequency-type daily

REM Example 5: Fetch market movers for SPX index
REM python schwab_api_data_fetcher.py --symbols SPX --data-type movers

REM Example 6: Fetch option chain for AAPL
REM python schwab_api_data_fetcher.py --symbols AAPL --data-type option-chain --output json

echo.
echo =============================================
echo Running Schwab API Data Fetcher with default parameters:
echo - Symbols: AAPL, MSFT, GOOGL
echo - Data Type: quotes
echo - Output Format: table
echo =============================================
echo.

REM Execute the script with default parameters
python schwab_api_data_fetcher.py --symbols AAPL,MSFT,GOOGL

REM Check if the script executed successfully
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ERROR: The script failed to execute properly.
    echo Please check the error messages above.
) else (
    echo.
    echo =============================================
    echo Script executed successfully!
    echo.
    echo To run with different parameters, either:
    echo 1. Edit this batch file
    echo 2. Run the Python script directly with your desired parameters
    echo    Example: python schwab_api_data_fetcher.py --symbols SPY --data-type price-history
    echo =============================================
)

REM Deactivate virtual environment if it was activated
if exist "venv\Scripts\activate.bat" (
    call venv\Scripts\deactivate.bat
)

echo.
pause