@echo off
REM ============================================================================
REM Schwab API Integration Tests Runner
REM ============================================================================
REM
REM Purpose: This batch file runs the Schwab API integration tests with proper
REM          environment setup and error handling.
REM
REM Author:  Generated by Roo
REM Date:    April 29, 2025
REM ============================================================================

echo.
echo Schwab API Integration Tests
echo =============================================
echo.

REM Set up environment variables for testing
set PYTHONPATH=%~dp0
set SCHWAB_TEST_MODE=True
set SCHWAB_API_MOCK=True

REM Check if Python is installed
where python >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Python is not installed or not in the PATH.
    echo Please install Python 3.10 or higher and try again.
    goto :error
)

REM Check Python version
python --version | findstr /r "3\.[1-9][0-9]" >nul
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Python version may not be compatible.
    echo Recommended: Python 3.10 or higher.
    echo.
    timeout /t 3
)

REM Check if pytest is installed
python -c "import pytest" 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: pytest is not installed.
    echo Installing pytest...
    python -m pip install pytest pytest-cov
    if %ERRORLEVEL% NEQ 0 (
        echo Failed to install pytest. Please install it manually:
        echo python -m pip install pytest pytest-cov
        goto :error
    )
)

REM Check if pytest-cov is installed
set COVERAGE_ENABLED=False
python -c "import pytest_cov" 2>nul
if %ERRORLEVEL% EQU 0 (
    set COVERAGE_ENABLED=True
) else (
    echo WARNING: pytest-cov is not installed.
    echo Installing pytest-cov...
    python -m pip install pytest-cov
    python -c "import pytest_cov" 2>nul
    if %ERRORLEVEL% EQU 0 (
        set COVERAGE_ENABLED=True
        echo pytest-cov installed successfully.
    ) else (
        echo Failed to install pytest-cov. Coverage reporting will be disabled.
    )
)

REM Activate virtual environment if it exists
if exist "venv\Scripts\activate.bat" (
    call venv\Scripts\activate.bat
    echo Virtual environment activated.
) else (
    echo No virtual environment found. Using system Python.
)

echo.
echo =============================================
echo Running Schwab API Integration Tests
echo =============================================
echo.

REM Create test results directory if it doesn't exist
if not exist "test_results" mkdir test_results

REM Run the tests with or without coverage based on availability
if "%COVERAGE_ENABLED%"=="True" (
    echo Running tests with coverage...
    python -m pytest tests\schwab_api\test_schwab_api_integration.py -v --cov=schwab_api --cov-report=term --cov-report=html:test_results\coverage
) else (
    echo Running tests without coverage (pytest-cov not available)...
    python -m pytest tests\schwab_api\test_schwab_api_integration.py -v
)

REM Check if tests passed
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo =============================================
    echo ERROR: Some tests failed!
    echo See the output above for details.
    echo =============================================
    goto :error
) else (
    echo.
    echo =============================================
    echo All tests passed successfully!
    echo =============================================
)

REM Run specific test categories if needed
echo.
echo Running OAuth authentication tests...
python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestSchwabAPIIntegration -v

echo.
echo Running market data fetching tests...
python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestMarketDataFetching -v

echo.
echo Running error handling tests...
python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestErrorHandling -v

echo.
echo =============================================
echo Test Summary
echo =============================================
echo.
if "%COVERAGE_ENABLED%"=="True" (
    echo Coverage report is available in test_results\coverage\index.html
) else (
    echo Coverage reporting was disabled due to missing pytest-cov plugin.
)
echo.
echo To run specific test classes:
echo   python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestSchwabAPIIntegration
echo   python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestMarketDataFetching
echo   python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestErrorHandling
echo.
echo To run a specific test:
echo   python -m pytest tests\schwab_api\test_schwab_api_integration.py::TestSchwabAPIIntegration::test_oauth_authentication_success
echo.

REM Deactivate virtual environment if it was activated
if exist "venv\Scripts\activate.bat" (
    call venv\Scripts\deactivate.bat
)

goto :end

:error
echo.
echo Test execution failed with errors.
exit /b 1

:end
echo.
echo Test execution completed.
pause